/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ChatRouteImport } from './routes/chat'
import { Route as TasksRouteImport } from './routes/tasks'
import { Route as ImagesIndexRouteImport } from './routes/images.index'
import { Route as ImagesAssetIdRouteImport } from './routes/images.$assetId'
import { Route as ImagesTrendsRouteImport } from './routes/images.trends'
import { Route as ImagesAssetIdReferencesRouteImport } from './routes/images.$assetId_.references'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ChatRoute = ChatRouteImport.update({
  id: '/chat',
  path: '/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const TasksRoute = TasksRouteImport.update({
  id: '/tasks',
  path: '/tasks',
  getParentRoute: () => rootRouteImport,
} as any)
const ImagesIndexRoute = ImagesIndexRouteImport.update({
  id: '/images/',
  path: '/images/',
  getParentRoute: () => rootRouteImport,
} as any)
const ImagesAssetIdRoute = ImagesAssetIdRouteImport.update({
  id: '/images/$assetId',
  path: '/images/$assetId',
  getParentRoute: () => rootRouteImport,
} as any)
const ImagesTrendsRoute = ImagesTrendsRouteImport.update({
  id: '/images/trends',
  path: '/images/trends',
  getParentRoute: () => rootRouteImport,
} as any)
const ImagesAssetIdReferencesRoute = ImagesAssetIdReferencesRouteImport.update({
  id: '/images/$assetId_/references',
  path: '/images/$assetId/references',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/chat': typeof ChatRoute
  '/tasks': typeof TasksRoute
  '/images/$assetId': typeof ImagesAssetIdRoute
  '/images/trends': typeof ImagesTrendsRoute
  '/images/': typeof ImagesIndexRoute
  '/images/$assetId/references': typeof ImagesAssetIdReferencesRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/chat': typeof ChatRoute
  '/tasks': typeof TasksRoute
  '/images/$assetId': typeof ImagesAssetIdRoute
  '/images/trends': typeof ImagesTrendsRoute
  '/images': typeof ImagesIndexRoute
  '/images/$assetId/references': typeof ImagesAssetIdReferencesRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/chat': typeof ChatRoute
  '/tasks': typeof TasksRoute
  '/images/$assetId': typeof ImagesAssetIdRoute
  '/images/trends': typeof ImagesTrendsRoute
  '/images/': typeof ImagesIndexRoute
  '/images/$assetId_/references': typeof ImagesAssetIdReferencesRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/chat'
    | '/tasks'
    | '/images/$assetId'
    | '/images/trends'
    | '/images/'
    | '/images/$assetId/references'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/chat'
    | '/tasks'
    | '/images/$assetId'
    | '/images/trends'
    | '/images'
    | '/images/$assetId/references'
  id:
    | '__root__'
    | '/'
    | '/chat'
    | '/tasks'
    | '/images/$assetId'
    | '/images/trends'
    | '/images/'
    | '/images/$assetId_/references'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ChatRoute: typeof ChatRoute
  TasksRoute: typeof TasksRoute
  ImagesAssetIdRoute: typeof ImagesAssetIdRoute
  ImagesTrendsRoute: typeof ImagesTrendsRoute
  ImagesIndexRoute: typeof ImagesIndexRoute
  ImagesAssetIdReferencesRoute: typeof ImagesAssetIdReferencesRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chat': {
      id: '/chat'
      path: '/chat'
      fullPath: '/chat'
      preLoaderRoute: typeof ChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tasks': {
      id: '/tasks'
      path: '/tasks'
      fullPath: '/tasks'
      preLoaderRoute: typeof TasksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/images/': {
      id: '/images/'
      path: '/images'
      fullPath: '/images/'
      preLoaderRoute: typeof ImagesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/images/$assetId': {
      id: '/images/$assetId'
      path: '/images/$assetId'
      fullPath: '/images/$assetId'
      preLoaderRoute: typeof ImagesAssetIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/images/trends': {
      id: '/images/trends'
      path: '/images/trends'
      fullPath: '/images/trends'
      preLoaderRoute: typeof ImagesTrendsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/images/$assetId_/references': {
      id: '/images/$assetId_/references'
      path: '/images/$assetId/references'
      fullPath: '/images/$assetId/references'
      preLoaderRoute: typeof ImagesAssetIdReferencesRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ChatRoute: ChatRoute,
  TasksRoute: TasksRoute,
  ImagesAssetIdRoute: ImagesAssetIdRoute,
  ImagesTrendsRoute: ImagesTrendsRoute,
  ImagesIndexRoute: ImagesIndexRoute,
  ImagesAssetIdReferencesRoute: ImagesAssetIdReferencesRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
